### ISSUE TITLE
Switching screen orientation on mobile resets contents of page

### ISSUE THREAD

**Issue by MysticalApple** [GunnWATT/watt#101]
Happens on iPhone 12 running iOS 15.5, unsure about other devices/OS

**Comment by MysticalApple** [comment]
Might be related to #35

**Comment by ky28059** [comment]
By contents of page, do you mean that it switches the tab? Or do you mean that the tab stays the same, but the physical page contents (eg. inputs, toggles) become reset?

Also, is this happening on `/clubs` or `/utilities` / `/settings`? Clubs uses state-based tabs where refreshing the page should switch the tab back to default as the active tab is merely stored in memory, but utilities and settings use nav-tabs where the tab is linked to the current path and refreshing the page should preserve the active tab.

**Comment by ky28059** [comment]
I failed to reproduce this on my iPhone 8 (iOS 15.5) so could you attach images or a video of the problem?

**Comment by MysticalApple** [comment]
Strangely enough this only seems occurs when going from horizontal to portrait when added to home screen, and has the same behavior as refreshing the page. On home screen the date is reset, in clubs the tab is reset, in utilities the tab remains the same but all input fields are wiped and the map closes, etc.

**Comment by ky28059** [comment]
![image](https://user-images.githubusercontent.com/60120929/179591262-75fd356a-4abb-4489-8c5a-344e021fc2c7.png)

I suspect this is related to the iPhone 12 screen, when viewed horizontally, being wide enough to exceed the breakpoint for a medium-sized screen and cause a full layout rerender. Going from a medium to phone screen width in inspect element does cause the behavior you describe.

Funnily enough, the "rerendering the whole app" issue was fixed in #96 (at least according to web emulator, you can test on preview URL) when layout was reworked to not return different `<div>`s depending on screen size. I think the only thing left to do is to make the sidebar rendered when viewing in horizontal actually function on such a short screen height.
