### ISSUE TITLE
Layout bugs out on medium sized screens on specific days

### ISSUE THREAD

**Issue by ky28059** [GunnWATT/watt#41]
![image](https://user-images.githubusercontent.com/60120929/130530816-e90fb7cb-7234-46ec-bd96-90cd609aac02.png)
Some dates that this happens on:
Tues. Aug 24, Wed. Aug 25, Thurs. Aug 19

**Comment by ky28059** [comment]
![image](https://user-images.githubusercontent.com/60120929/130530948-4b65d163-6daa-4196-88dd-7cea04a6732e.png)
![image](https://user-images.githubusercontent.com/60120929/130530959-ac4eb0f9-1155-4103-85ac-fff5a5990312.png)
Seems to be related with the length of Events

**Comment by ky28059** [comment]
![image](https://user-images.githubusercontent.com/60120929/130531400-88c4ca99-0382-4a92-b76e-48167c71f08f.png)
Setting a fixed width for Events fixes it, but why is it allowed to expand past 100%?

**Comment by SheepTester** [comment]
Probably because of the Zoom link? Did you give it `word-break: break-word;`?

**Comment by SheepTester** [comment]
Giving `flex: none;` to `.sidebar` fixes it

![image](https://user-images.githubusercontent.com/22133785/130533819-ee4fd91c-8b77-4b71-a088-dd7cbdeb75f1.png)

I think it's because the long event description on that day stretches `.content`, which squishes the sidebar

I probably accidentally introduced this when I moved the sidebar itself into a child `.sidebar-content`; there's a `flex: none;` on `.sidebar-content` (formerly just `.sidebar`) which is why this didn't happen before, but when I separated the two, I forgot to move `flex: none;` from `.sidebar-content` to `.sidebar`
