### ISSUE TITLE
Classes tab errors on "fetch materials" click

### ISSUE THREAD

**Issue by ky28059** [GunnWATT/watt#79]
![image](https://user-images.githubusercontent.com/60120929/147843302-cec4fb35-cb15-489e-8e53-d16f3d8135cb.png)

### Steps to reproduce:
1. Go to the Classes tab.
2. Click the `Fetch` button. 
3. Wait for the "Something went wrong" screen to appear.
<img alt="image" src="https://user-images.githubusercontent.com/60120929/147843278-f45f2484-c72f-47d7-bc32-f8734b12bacd.png">

Switching away and back to the tab causes the screen to disappear, so it might be something to do with intermediate rendering of the page during the fetch triggering some conditional when the user data disappears temporarily.

**Comment by ky28059** [comment]
This also happens when the periodic fetch in the `useEffect` happens.

**Comment by ImNotRog** [comment]
Fascinating; this bug did not occur before. I will look into it, but for reference, here are the factors that cause this issue:

Making 2 calls to the function fetch-materials within 5 seconds will cause both calls to crash, because of Schoology api rate limiting. Because of how functions works without any variables, and how Schoology outright rejects calls over rate limits, this is pretty difficult to fix.

Thus, it becomes important to prevent this issue on the client side, which is why localStorage stores the last fetched time per device, and why it does not let you fetch until 5 seconds after the last fetch.

**Comment by ImNotRog** [comment]
Closed with https://github.com/GunnWATT/watt/commit/8601d5c507f3ea90a0ee82ce1a33a1e95dabf5b1.
